apiVersion: v1
kind: Secret
metadata:
  name: autovox-secret
  namespace: autovox
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "replace-with-a-long-random-secret"
  EMAIL_HOST_USER: "k.balaji2312@gmail.com"
  EMAIL_HOST_PASSWORD: "replace-with-google-app-password"
