apiVersion: v1
kind: Service
metadata:
  name: autovox-service
  namespace: autovox
spec:
  type: ClusterIP
  selector:
    app: autovox-web
  ports:
    - name: http
      port: 80
      targetPort: 8000
